### ISSUE TITLE
Handle ਯ variations with Unicode Variation Selectors

### ISSUE THREAD

**Issue by akshdeep-singh** [shabados/SantLipi#42]
Current workaround for handling ਯ variations is using ligatures with Indic fractions. However, the Indic fractions are a possible word-break.

Better solution is to use the Standard Unicode Variation Selectors.

[Slack Discussion](https://shabados.slack.com/archives/C03P11B1WA1/p1691326176175209).

**Comment by akshdeep-singh** [comment]
Possible combinations:

<img width="591" alt="image" src="https://github.com/shabados/SantLipi/assets/50951164/a1730c5b-30b3-4bf0-983c-d8e4261d1eb8">

More info about Variation Selectors:
https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)
http://unicode.org/faq/vs.html

**Comment by bhajneet** [comment]
For it to work the VS has to come before the character. And in Sant Lipi we take any Virama and convert it to a VS1.

Our features are as follows:

`ltra` (this will "rewrite" the input stream, before other features have a chance to modify it):

```
sub halant-gurmukhi' ya-gurmukhi by VS1;
```

`rlig`:

```
sub VS1 ya-gurmukhi by ya-gurmukhi.uv001.rlig;
sub VS2 ya-gurmukhi by ya-gurmukhi.uv002.rlig;
sub VS3 ya-gurmukhi by ya-gurmukhi.uv003.rlig;
```

**Comment by bhajneet** [comment]
Quick explanation:

Ya + VS1 + Kanna (ਯ + VS1 + ਾ) will show an unattached ਾ

**Comment by akshdeep-singh** [comment]
But Unicode Standard says the VS are for the [preceding](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)#:~:text=Variation%20Selectors%20is%20the%20block%20name%20of%20a%20Unicode%20code%20point%20block%20containing%2016%20variation%20selectors%20used%20to%20specify%20a%20glyph%20variant%20for%20a%20preceding%20character.) character.

**Comment by bhajneet** [comment]
The Unicode Standard will not work with Gurmukhi. We are unable to use mark attachments on Variation Selectors.

So for example Ya + VS1 + Kanna (ਯ + VS1 + ਾ) will show an unattached ਾ as in:

<img width="277" alt="image" src="https://github.com/shabados/SantLipi/assets/14130567/7a57842a-bca1-4264-90bd-8d0e87bc7634">

**Comment by akshdeep-singh** [comment]
> The Unicode Standard will not work with Gurmukhi. We are unable to use mark attachments on Variation Selectors.
> 
> So for example Ya + VS1 + Kanna (ਯ + VS1 + ਾ) will show an unattached ਾ as in:
> 
> <img alt="image" width="277" src="https://user-images.githubusercontent.com/14130567/258649598-7a57842a-bca1-4264-90bd-8d0e87bc7634.png">

That will be for Normal fonts I think, can't you do something for SantLipi?

**Comment by bhajneet** [comment]
The Unicode Standard is assuming the use of VS on something like a plain character or mathematical operator or chinese character singleton. It's not for composing characters in Indic languages

**Comment by akshdeep-singh** [comment]
I think you're right. One more advantage is that we can put VS1 before any consonant, and normal fonts just don't show it. So, we do not have to care about Gurmukhi <-> SantLipi conversion. We can keep the VS in the text as is for Gurmukhi also.

**Comment by bhajneet** [comment]
I mean we could write more complex rules, but it's not like VS is even approved for Gurmukhi, so it's not going to be standardized either way.

> That will be for Normal fonts I think, can't you do something for SantLipi?

There are a couple ways of looking at it:

1) Consider VS1 as "open-top" and add it to the base yayya + half-yayya. So you can have 4 yayya variants with simply the two existing yayyas and optional VS1
2) Consider half-yayya as it's own character, this makes vowel attachments simpler, and is the correct way for unicode to work, if they want to support complex vowel attachments, as we have in our database. So then you are looking at one yayya and 3 variants of it.

2 is definitely the way we will have to go about it to support something like the following:

<img width="30" alt="image" src="https://github.com/shabados/SantLipi/assets/14130567/b7cb1b54-9195-4e40-a2b6-fca6d03f4c3c">

This above one will never work with the way Unicode classifies half-yayya to be dependent, because vowels are being applied to the combined base+half-yayya. It does not treat half-yayya as it's own character.

Now the only two options I really see are:

1) VS + Yayya + Mark Attachments
2) Yayya + VS + Mark Attachments
3) Yayya + Mark Attachments + VS

Obviously 2 doesn't work as shown above. The easier solution is definitely to use VS as a preceding markup indicator. This allows us to easily replace the virama yayya combo with vs yayya combo as well. This is what let's Sant Lipi to render ਕੀ੍ਯੋ correctly. In your browser (with a typical unicode font) you will see ਕੀ + ੍ਯੋ, but the exact same sequence in Sant Lipi (using a virama, not VS) will correctly show:

<img width="30" alt="image" src="https://github.com/shabados/SantLipi/assets/14130567/b7cb1b54-9195-4e40-a2b6-fca6d03f4c3c">

Option 3 to lookup Yayya + Mark Attachments + VS at the end of the composed character would require very complex rules. I would have to lookup combos of yayya and all the different mark attachments we have (including virama + base char) and then look for a VS at the end just to re-render the yayya. And in addition to re-write the input stream to handle virama would be very complex as well. We would lose support for typical virama usage, simply because fonts today don't know how to handle half-yayya.

So, even though the Unicode Standard is to use VS on a preceding character, I really think (considering it's not going to be standardized anyways) to just use it incorrectly for simpler rule structures and easier virama+yayya rewriting.

**Comment by bhajneet** [comment]
Another idea I had is we can probably stack VS together. That way VS usage becomes more idiomatic.

For example:

- VS1 = open left-side (can be used for ya, ma, tha)
- VS2 = open top-side

And to get an open-top half-yayya we could do VS1 + VS2 + Ya

This would fit in better with the Mahan Kosh variants as well I'm guessing
